name: Update Train Speed Averages

on:
  schedule:
    - cron: "*/1 12-23 * * *" # 8am–7:59pm ET
    - cron: "*/1 0-3 * * *" # 8pm–10:59pm ET
  workflow_dispatch:

jobs:
  update-averages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          WMATA_API_KEY: ${{ secrets.WMATA_API_KEY }}
        run: python wmata_speed_updater.py

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add circuit_rolling_averages.json
          git commit -m "Update circuit rolling averages"
          git push
